In [12]:
import pandas as pd
df=pd.read_csv('Automobile.csv')
# print(df.head())
print(df.isna().sum())

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

In [19]:
# cols=df.columns
# for col in cols:
# print(df[col].dtype)
df.head(12)

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,161,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,168,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
10,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
11,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970

In [20]:

categorical_columns = ['make', 'fuel_type', 'aspiration', 'number_of_doors', 'body_style', 'drive_wheels', 'engine_location', 'fuel_system']

for col in categorical_columns:
    df[col] = df[col].str.lower()  
    df[col] = df[col].str.replace(r'[^a-z0-9\s]', '', regex=True) 

print(df[categorical_columns].head())

         make fuel_type aspiration number_of_doors   body_style drive_wheels  \
0  alfaromero       gas        std             two  convertible          rwd
1  alfaromero       gas        std             two  convertible          rwd
2  alfaromero       gas        std             two    hatchback          rwd
3        audi       gas        std            four        sedan          fwd
4        audi       gas        std            four        sedan          4wd

  engine_location fuel_system
0           front        mpfi
1           front        mpfi
2           front        mpfi
3           front        mpfi
4           front        mpfi

In [21]:
# Replace '?' with appropriate replacements in categorical columns
df['make'].replace('?', 'unknown', inplace=True)
df['fuel_type'].replace('?', 'gas', inplace=True)
df['aspiration'].replace('?', 'std', inplace=True)
df['number_of_doors'].replace('?', 'four', inplace=True)
df['body_style'].replace('?', 'sedan', inplace=True)
df['drive_wheels'].replace('?', 'fwd', inplace=True)
df['engine_location'].replace('?', 'front', inplace=True)
df['fuel_system'].replace('?', 'mpfi', inplace=True)

df['price'] = pd.to_numeric(df['price'], errors='coerce')  # Convert to numeric
df['price'].fillna(df['price'].median(), inplace=True)  # Replace NaN and ?

# Similarly, for other numerical columns
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df['horsepower'].fillna(df['horsepower'].median(), inplace=True)

In [23]:
df['number_of_cylinders'] = df['number_of_cylinders'].replace({
    'four': 4,
    'six': 6,
    'eight': 8
})

In [25]:
# Standardize 'fuel_system' categories
df['fuel_system'] = df['fuel_system'].replace({
    'spdi': 'mpfi',
    'multi-point fuel injection': 'mpfi',
    'single-point fuel injection': 'spfi'
})

print(df[categorical_columns + ['number_of_cylinders', 'fuel_system']].head())

         make fuel_type aspiration number_of_doors   body_style drive_wheels  \
0  alfaromero       gas        std             two  convertible          rwd
1  alfaromero       gas        std             two  convertible          rwd
2  alfaromero       gas        std             two    hatchback          rwd
3        audi       gas        std            four        sedan          fwd
4        audi       gas        std            four        sedan          4wd

  engine_location fuel_system number_of_cylinders fuel_system
0           front        mpfi                   4        mpfi
1           front        mpfi                   4        mpfi
2           front        mpfi                   6        mpfi
3           front        mpfi                   4        mpfi
4           front        mpfi                five        mpfi

In [31]:
# converting hoser power and peak rpm to integers
df['horsepower'] = df['horsepower'].astype(int)
df['peak_rpm'] = df['peak_rpm'].astype(int)
# Convert to numeric for price, invalid becomes NaN
df['price'] = pd.to_numeric(df['price'], errors='coerce')
# print(df.isna().sum())
df['horsepower_kW'] = df['horsepower'] * 0.7457

df['horsepower_kW']

0       82.7727
1       82.7727
2      114.8378
3       76.0614
4       85.7555
         ...
196     85.0098
197    119.3120
198     99.9238
199     79.0442
200     85.0098
Name: horsepower_kW, Length: 201, dtype: float64

In [32]:
# Power-to-weight ratio = horsepower / curb_weight
df['power_to_weight'] = df['horsepower'] / df['curb_weight']

# Engine efficiency = horsepower / engine_size
df['engine_efficiency'] = df['horsepower'] / df['engine_size']

# Fuel efficiency = city_mpg / highway_mpg
df['fuel_efficiency'] = df['city_mpg'] / df['highway_mpg']

# Convert compression_ratio into categories
def categorize_compression_ratio(x):
    if x < 9:
        return 'Low'
    elif 9 <= x <= 11:
        return 'Medium'
    else:
        return 'High'

# Apply the function to the compression_ratio column
df['compression_ratio_category'] = df['compression_ratio'].apply(categorize_compression_ratio)

# Display the first few rows of the new columns
print(df[['power_to_weight', 'engine_efficiency', 'fuel_efficiency', 'compression_ratio_category']].head())

   power_to_weight  engine_efficiency  fuel_efficiency  \
0         0.043564           0.853846         0.777778
1         0.043564           0.853846         0.777778
2         0.054552           1.013158         0.730769
3         0.043646           0.935780         0.800000
4         0.040722           0.845588         0.818182

  compression_ratio_category
0                     Medium
1                     Medium
2                     Medium
3                     Medium
4                        Low